### ISSUE TITLE
Grid parameter incompatible with Interval

### ISSUE THREAD

**Issue by GrayFace** [amietn/vcsi#54]
Instead of generating grid of proper height that fits all generated frames (aka samples), VCSI either throws them away or adds blackness below the grid of actual frames.

E.g.
1) --interval 10s -g 5x1
Creates 5x1 grid instead of sufficiently big grid.
2) --interval 10s -g 5x0
vcsi.py: error: argument -g/--grid: Grid must be of the form mxn, where m is the
 number of columns and n is the number of rows.
3) --interval 10s -g 5x200
Creates an image of huge height, most of which is black.

**Comment by GrayFace** [comment]
Made a fix for it (public domain):
Search "if args.grid == DEFAULT_GRID_SIZE:", add
`        else:
            y = math.ceil(args.num_samples / args.grid.x)
            args.grid = Grid(args.grid.x, y)
`

**Comment by amietn** [comment]
If I understand correctly, what you want is to have some way to set a fixed number of columns and have the number of rows automatically deduced based on the `--interval` parameter.

As you have noticed, currently the `--grid` parameter will do exactly what you tell it to do. You also noticed that a grid with a number of rows or columns equal to zero is currently not supported.

The fix in your comment above does not allow setting a fixed number of rows. It assumes the user wants a fixed number of columns.

I suggest the following change:

Make grid parameters such as 5x0 or 0x5 (or 5xauto or autox5) a valid syntax, such that one can decide whether the number of columns or rows should be fixed.

Personally I would go for "5x0" instead of "5xauto" since it is shorter.

Would that change provide the behavior that you need?

**Comment by GrayFace** [comment]
Yes, I used the same logic that is applied when setting num_samples manually. Accepting 0 or auto would be more versatile for both.

**Comment by amietn** [comment]
Ok :) I will try and implement that.

**Comment by amietn** [comment]
Should be fixed in https://github.com/amietn/vcsi/commit/135dbfb7a952c3da56bd2ab7ca928475d333ac8e
