### ISSUE TITLE
Temporary files are not deleted

### ISSUE THREAD

**Issue by mxmlnkn** [amietn/vcsi#68]
While running vcsi for quite a lot of files, I noticed my /tmp folder becoming huge and saw that it contained thousands of PNG images. It looks like vcsi does not delete temporary files after it is done.  It'd be nice if it did that, though.

**Comment by amietn** [comment]
Thank you for reporting this issue.

What is the version of vcsi that you are running?

`vcsi --version`

Can you provide the command that you used?

**Comment by mxmlnkn** [comment]
vcsi version 7.0.12

vcsi --quality 75 --width 1200 --grid 4x4 --metadata-position hidden --output thumb.jpg video.mkv

Looking at the source code you are using: `tempfile.mkstemp(suffix=suffix)` but you are only closing the descriptor and I can't find any call to `os.remove`.

**Comment by amietn** [comment]
I tried to reproduce the issue with the same command but failed.

I checked the code and it appears that os.unlink() is called for all frames, regardless whether the frame was selected or not.

My guess is that os.unlink() fails for some reason and no error is shown because of the

```
except:
    pass
```

I just pushed a commit (https://github.com/amietn/vcsi/commit/1d5e55eed359e642d24dd2198d7c0832dc6033a8) that adds some debug messages that will appear only when run with `--verbose`. Can you try again with the latest git master version and print the output of the same command but with `--verbose`?

Hopefully this will help troubleshooting the issue.

**Comment by mxmlnkn** [comment]
One suspicious output was: 

    ~/.local/lib/python3.7/site-packages/vcsi/vcsi.py:584: RuntimeWarning: divide by zero encountered in double_scalars
      return 1 / max_freq

But that might have happened because of an invalid video file.

But aside from that, I think know now how I came upon this problem. I called vcsi from another python script and during testing I interrupted that very often with Ctrl+C. The leftover files were from those interrupts; I can reproduce it. A trap for the cleanup would be nice but at least I now know that it doesn't grow automatically to infinity except if it is somehow called e.g. inside a subprocess with a timeout.

Sorry for the trouble.
