### ISSUE TITLE
Configuration File Error

### ISSUE THREAD

**Issue by remlap** [amietn/vcsi#81]
I am trying to setup a conf file but I get this error:

[ERROR] File contains no section headers.
file: '/home/remlap/.config/vcsi.conf', line: 1
'quality=90\n'

My conf settings:

quality=90
metadata-font-size=20
template=/home/remlap/.vcsitemplate
background-color=ffffff
metadata-font-color=000000
show-timestamp
grid=3x4
actual-size

**Comment by amietn** [comment]
Hello @remlap ,

The config file needs to start with a `[vcsi]` header. It should look like this:

~/.config/vcsi.conf:

```
[vcsi]
quality=90
metadata-font-size=20
template=/home/remlap/.vcsitemplate
...
```

The `--show-timestamp` and `--actual-size` arguments are currently not supported via the config file. This will be fixed in the future. For now you will have to pass them on the command line until it is fixed.

**Comment by glottisfaun0000** [comment]
> The `--show-timestamp` and `--actual-size` arguments are currently not supported via the config file. This will be fixed in the future. For now you will have to pass them on the command line until it is fixed.

Is this being worked on?
